/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/models/assets/models/f1_2023_mercedes_amg_w14_e_performance_s1.glb -o src/components/CarModel.tsx -t 
Author: MattsActuallyUsefulModels (https://sketchfab.com/MattsActuallyUsefulModels)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/f1-2023-mercedes-amg-w14-e-performance-s1-0fbfb7843e494026bba55a912a2c3fa2
Title: F1 2023 Mercedes AMG W14 E Performance S1
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
    Object_16: THREE.Mesh
    Object_18: THREE.Mesh
    Object_20: THREE.Mesh
    Object_22: THREE.Mesh
    Object_24: THREE.Mesh
    Object_26: THREE.Mesh
    Object_28: THREE.Mesh
    Object_30: THREE.Mesh
    Object_32: THREE.Mesh
    Object_34: THREE.Mesh
    Object_36: THREE.Mesh
    Object_38: THREE.Mesh
    Object_40: THREE.Mesh
    Object_42: THREE.Mesh
    Object_44: THREE.Mesh
    Object_46: THREE.Mesh
    Object_48: THREE.Mesh
    Object_50: THREE.Mesh
    Object_52: THREE.Mesh
    Object_54: THREE.Mesh
    Object_56: THREE.Mesh
    Object_58: THREE.Mesh
    Object_60: THREE.Mesh
    Object_62: THREE.Mesh
    Object_64: THREE.Mesh
    Object_66: THREE.Mesh
    Object_68: THREE.Mesh
    Object_71: THREE.Mesh
    Object_73: THREE.Mesh
    Object_75: THREE.Mesh
    Object_77: THREE.Mesh
    Object_79: THREE.Mesh
    Object_82: THREE.Mesh
    Object_84: THREE.Mesh
    Object_86: THREE.Mesh
    Object_88: THREE.Mesh
    Object_90: THREE.Mesh
    Object_93: THREE.Mesh
    Object_95: THREE.Mesh
    Object_97: THREE.Mesh
    Object_99: THREE.Mesh
    Object_101: THREE.Mesh
    Object_104: THREE.Mesh
    Object_106: THREE.Mesh
    Object_108: THREE.Mesh
    Object_110: THREE.Mesh
    Object_112: THREE.Mesh
    Object_115: THREE.Mesh
    Object_117: THREE.Mesh
    Object_119: THREE.Mesh
    Object_121: THREE.Mesh
    Object_123: THREE.Mesh
    Object_126: THREE.Mesh
    Object_128: THREE.Mesh
    Object_131: THREE.Mesh
    Object_133: THREE.Mesh
    Object_136: THREE.Mesh
    Object_138: THREE.Mesh
    Object_140: THREE.Mesh
    Object_142: THREE.Mesh
    Object_144: THREE.Mesh
    Object_147: THREE.Mesh
    Object_149: THREE.Mesh
    Object_151: THREE.Mesh
    Object_153: THREE.Mesh
    Object_155: THREE.Mesh
    Object_158: THREE.Mesh
    Object_160: THREE.Mesh
    Object_162: THREE.Mesh
    Object_164: THREE.Mesh
    Object_166: THREE.Mesh
    Object_169: THREE.Mesh
    Object_171: THREE.Mesh
    Object_173: THREE.Mesh
    Object_175: THREE.Mesh
    Object_177: THREE.Mesh
    Object_179: THREE.Mesh
    Object_181: THREE.Mesh
    Object_183: THREE.Mesh
    Object_185: THREE.Mesh
    Object_187: THREE.Mesh
    Object_189: THREE.Mesh
    Object_191: THREE.Mesh
    Object_193: THREE.Mesh
    Object_195: THREE.Mesh
    Object_197: THREE.Mesh
    Object_199: THREE.Mesh
    Object_201: THREE.Mesh
    Object_203: THREE.Mesh
    Object_205: THREE.Mesh
    Object_207: THREE.Mesh
    Object_209: THREE.Mesh
    Object_211: THREE.Mesh
    Object_213: THREE.Mesh
    Object_215: THREE.Mesh
    Object_217: THREE.Mesh
    Object_219: THREE.Mesh
    Object_221: THREE.Mesh
    Object_223: THREE.Mesh
    Object_225: THREE.Mesh
    Object_227: THREE.Mesh
    Object_229: THREE.Mesh
    Object_231: THREE.Mesh
    Object_233: THREE.Mesh
    Object_235: THREE.Mesh
    Object_237: THREE.Mesh
    Object_239: THREE.Mesh
    Object_241: THREE.Mesh
    Object_243: THREE.Mesh
    Object_245: THREE.Mesh
    Object_247: THREE.Mesh
    Object_249: THREE.Mesh
    Object_251: THREE.Mesh
    Object_253: THREE.Mesh
    Object_255: THREE.Mesh
    Object_257: THREE.Mesh
    Object_259: THREE.Mesh
    Object_262: THREE.Mesh
    Object_264: THREE.Mesh
    Object_267: THREE.Mesh
    Object_269: THREE.Mesh
    Object_271: THREE.Mesh
    Object_273: THREE.Mesh
    Object_275: THREE.Mesh
    Object_277: THREE.Mesh
    Object_280: THREE.Mesh
    Object_282: THREE.Mesh
    Object_284: THREE.Mesh
    Object_287: THREE.Mesh
    Object_289: THREE.Mesh
    Object_291: THREE.Mesh
    Object_294: THREE.Mesh
    Object_296: THREE.Mesh
    Object_299: THREE.Mesh
    Object_301: THREE.Mesh
    Object_304: THREE.Mesh
    Object_306: THREE.Mesh
    Object_308: THREE.Mesh
    Object_310: THREE.Mesh
    Object_312: THREE.Mesh
    Object_314: THREE.Mesh
    Object_317: THREE.Mesh
    Object_319: THREE.Mesh
    Object_321: THREE.Mesh
    Object_323: THREE.Mesh
    Object_325: THREE.Mesh
    Object_327: THREE.Mesh
    Object_330: THREE.Mesh
    Object_332: THREE.Mesh
    Object_334: THREE.Mesh
    Object_336: THREE.Mesh
    Object_338: THREE.Mesh
    Object_340: THREE.Mesh
    Object_343: THREE.Mesh
    Object_345: THREE.Mesh
    Object_347: THREE.Mesh
    Object_349: THREE.Mesh
    Object_351: THREE.Mesh
    Object_353: THREE.Mesh
    Object_355: THREE.Mesh
    Object_357: THREE.Mesh
    Object_359: THREE.Mesh
    Object_361: THREE.Mesh
    Object_363: THREE.Mesh
    Object_366: THREE.Mesh
    Object_368: THREE.Mesh
    Object_370: THREE.Mesh
    Object_372: THREE.Mesh
    Object_374: THREE.Mesh
    Object_376: THREE.Mesh
    Object_378: THREE.Mesh
    Object_380: THREE.Mesh
    Object_382: THREE.Mesh
    Object_384: THREE.Mesh
    Object_386: THREE.Mesh
    Object_388: THREE.Mesh
    Object_390: THREE.Mesh
    Object_392: THREE.Mesh
    Object_394: THREE.Mesh
    Object_396: THREE.Mesh
    Object_398: THREE.Mesh
    Object_400: THREE.Mesh
    Object_402: THREE.Mesh
    Object_404: THREE.Mesh
    Object_406: THREE.Mesh
    Object_408: THREE.Mesh
    Object_410: THREE.Mesh
    Object_412: THREE.Mesh
    Object_414: THREE.Mesh
    Object_416: THREE.Mesh
    Object_418: THREE.Mesh
    Object_421: THREE.Mesh
    Object_423: THREE.Mesh
    Object_425: THREE.Mesh
    Object_427: THREE.Mesh
    Object_429: THREE.Mesh
    Object_431: THREE.Mesh
    Object_433: THREE.Mesh
    Object_437: THREE.Mesh
    Object_440: THREE.Mesh
    Object_442: THREE.Mesh
    Object_444: THREE.Mesh
    Object_446: THREE.Mesh
    Object_449: THREE.Mesh
  }
  materials: {
    mercedes_carbon3: THREE.MeshStandardMaterial
    generics: THREE.MeshStandardMaterial
    mercedes_carbon1: THREE.MeshStandardMaterial
    mercedes_paint: THREE.MeshStandardMaterial
    mercedes_decal: THREE.MeshStandardMaterial
    mercedes_detail: THREE.MeshStandardMaterial
    mercedes_number: THREE.MeshStandardMaterial
    discs: THREE.MeshStandardMaterial
    mercedes_wheel_hub: THREE.MeshStandardMaterial
    ['TIRE_SIDES.001']: THREE.MeshStandardMaterial
    ['TIRE_TREAD.001']: THREE.MeshStandardMaterial
    mercedes_paint_alpha: THREE.MeshStandardMaterial
    mirror: THREE.MeshStandardMaterial
    ['erslight.001']: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    CLEARLED: THREE.MeshStandardMaterial
    sw_rotaries: THREE.MeshStandardMaterial
    SW_BLACK: THREE.MeshStandardMaterial
    SW_DECALS: THREE.MeshStandardMaterial
    SW_HANDLES: THREE.MeshStandardMaterial
    SW_MAIN: THREE.MeshStandardMaterial
    SW_METAL: THREE.MeshStandardMaterial
    SW_MONITOR_BACK: THREE.MeshStandardMaterial
    SW_PADDLES: THREE.MeshStandardMaterial
    SW_PLASTIC: THREE.MeshStandardMaterial
    material_25: THREE.MeshStandardMaterial
    TAG_DRS_ON: THREE.MeshStandardMaterial
    CLEARLED_PRE: THREE.MeshStandardMaterial
    driver_color: THREE.MeshStandardMaterial
    rear_light: THREE.MeshStandardMaterial
    mercedes_decal_2: THREE.MeshStandardMaterial
    cockpit_foam: THREE.MeshStandardMaterial
    cockpit: THREE.MeshStandardMaterial
    cockpit_metal: THREE.MeshStandardMaterial
    TCAM: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export default function CarModel(props: React.ComponentProps<"group">) {
  const { nodes, materials } = useGLTF('/assets/models/f1_2023_mercedes_amg_w14_e_performance_s1.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0.805, 0.366, 1.801]} rotation={[Math.PI / 2, 0.035, 0]}>
        <mesh geometry={nodes.Object_71.geometry} material={materials.discs} />
        <mesh geometry={nodes.Object_73.geometry} material={materials.mercedes_wheel_hub} />
        <mesh geometry={nodes.Object_75.geometry} material={materials['TIRE_SIDES.001']} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_77.geometry} material={materials['TIRE_TREAD.001']} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_79.geometry} material={materials.mercedes_wheel_hub} rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <group position={[0.805, 0.366, 1.801]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_82.geometry} material={materials.mercedes_carbon1} />
        <mesh geometry={nodes.Object_84.geometry} material={materials.mercedes_carbon3} />
        <mesh geometry={nodes.Object_86.geometry} material={materials.mercedes_carbon1} />
        <mesh geometry={nodes.Object_88.geometry} material={materials.mercedes_decal} />
        <mesh geometry={nodes.Object_90.geometry} material={materials.mercedes_paint_alpha} position={[-0.001, 0, -0.001]} />
      </group>
      <group position={[-0.805, 0.366, 1.801]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_93.geometry} material={materials.mercedes_carbon1} />
        <mesh geometry={nodes.Object_95.geometry} material={materials.mercedes_carbon3} />
        <mesh geometry={nodes.Object_97.geometry} material={materials.mercedes_carbon1} />
        <mesh geometry={nodes.Object_99.geometry} material={materials.mercedes_decal} />
        <mesh geometry={nodes.Object_101.geometry} material={materials.mercedes_paint_alpha} position={[0.001, 0, -0.001]} />
      </group>
      <group position={[-0.805, 0.366, 1.801]} rotation={[Math.PI / 2, -0.035, 0]}>
        <mesh geometry={nodes.Object_104.geometry} material={materials.discs} />
        <mesh geometry={nodes.Object_106.geometry} material={materials.mercedes_wheel_hub} />
        <mesh geometry={nodes.Object_108.geometry} material={materials['TIRE_SIDES.001']} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_110.geometry} material={materials['TIRE_TREAD.001']} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_112.geometry} material={materials.mercedes_wheel_hub} />
      </group>
      <group position={[-0.782, 0.359, -1.801]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_115.geometry} material={materials.discs} />
        <mesh geometry={nodes.Object_117.geometry} material={materials.mercedes_wheel_hub} />
        <mesh geometry={nodes.Object_119.geometry} material={materials['TIRE_SIDES.001']} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_121.geometry} material={materials['TIRE_TREAD.001']} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_123.geometry} material={materials.mercedes_wheel_hub} />
      </group>
      <group position={[-0.782, 0.359, -1.801]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_126.geometry} material={materials.mercedes_carbon3} position={[0.16, -0.02, 0]} />
        <mesh geometry={nodes.Object_128.geometry} material={materials.mercedes_carbon1} position={[0.16, -0.02, 0]} />
      </group>
      <group position={[0.782, 0.359, -1.801]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_131.geometry} material={materials.mercedes_carbon3} position={[-0.159, -0.02, 0]} />
        <mesh geometry={nodes.Object_133.geometry} material={materials.mercedes_carbon1} position={[-0.159, -0.02, 0]} />
      </group>
      <group position={[0.782, 0.359, -1.801]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_136.geometry} material={materials.discs} />
        <mesh geometry={nodes.Object_138.geometry} material={materials.mercedes_wheel_hub} />
        <mesh geometry={nodes.Object_140.geometry} material={materials['TIRE_SIDES.001']} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_142.geometry} material={materials['TIRE_TREAD.001']} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_144.geometry} material={materials.mercedes_wheel_hub} />
      </group>
      <group position={[0.446, 0.723, 0.82]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_147.geometry} material={materials.mirror} />
        <mesh geometry={nodes.Object_149.geometry} material={materials.mercedes_paint} />
        <mesh geometry={nodes.Object_151.geometry} material={materials.mercedes_detail} />
        <mesh geometry={nodes.Object_153.geometry} material={materials.mercedes_carbon1} />
        <mesh geometry={nodes.Object_155.geometry} material={materials.mercedes_carbon3} />
      </group>
      <group position={[-0.446, 0.723, 0.82]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_158.geometry} material={materials.mirror} />
        <mesh geometry={nodes.Object_160.geometry} material={materials.mercedes_paint} />
        <mesh geometry={nodes.Object_162.geometry} material={materials.mercedes_detail} />
        <mesh geometry={nodes.Object_164.geometry} material={materials.mercedes_carbon1} />
        <mesh geometry={nodes.Object_166.geometry} material={materials.mercedes_carbon3} />
      </group>
      <group position={[0, 0.601, 0.805]} rotation={[1.605, 0, 0]}>
        <mesh geometry={nodes.Object_169.geometry} material={materials['erslight.001']} position={[-0.043, -0.072, -0.004]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_171.geometry} material={materials['erslight.001']} position={[-0.043, -0.072, -0.007]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_173.geometry} material={materials['erslight.001']} position={[-0.043, -0.071, -0.027]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_175.geometry} material={materials['erslight.001']} position={[-0.043, -0.071, -0.029]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_177.geometry} material={materials['erslight.001']} position={[-0.043, -0.071, -0.032]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_179.geometry} material={materials['erslight.001']} position={[-0.043, -0.071, -0.034]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_181.geometry} material={materials['erslight.001']} position={[-0.043, -0.071, -0.036]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_183.geometry} material={materials['erslight.001']} position={[-0.043, -0.071, -0.038]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_185.geometry} material={materials['erslight.001']} position={[-0.043, -0.071, -0.041]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_187.geometry} material={materials['erslight.001']} position={[-0.043, -0.071, -0.043]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_189.geometry} material={materials['erslight.001']} position={[-0.043, -0.071, -0.045]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_191.geometry} material={materials['erslight.001']} position={[-0.043, -0.071, -0.048]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_193.geometry} material={materials['erslight.001']} position={[-0.043, -0.072, -0.009]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_195.geometry} material={materials['erslight.001']} position={[-0.043, -0.072, -0.011]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_197.geometry} material={materials['erslight.001']} position={[-0.043, -0.072, -0.013]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_199.geometry} material={materials['erslight.001']} position={[-0.043, -0.072, -0.016]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_201.geometry} material={materials['erslight.001']} position={[-0.043, -0.072, -0.018]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_203.geometry} material={materials['erslight.001']} position={[-0.043, -0.072, -0.02]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_205.geometry} material={materials['erslight.001']} position={[-0.043, -0.072, -0.023]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_207.geometry} material={materials['erslight.001']} position={[-0.043, -0.072, -0.025]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_209.geometry} material={materials.material} position={[0.002, -0.065, -0.014]} rotation={[-Math.PI / 2, 0, 0]} scale={1.01} />
        <mesh geometry={nodes.Object_211.geometry} material={materials.CLEARLED} position={[0.006, -0.07, -0.065]} scale={[1.348, 1.089, 1.348]} />
        <mesh geometry={nodes.Object_213.geometry} material={materials.CLEARLED} position={[-0.002, -0.014, -0.001]} scale={1.156} />
        <mesh geometry={nodes.Object_215.geometry} material={materials.CLEARLED} position={[0.006, -0.07, -0.064]} scale={[1.348, 1.089, 1.348]} />
        <mesh geometry={nodes.Object_217.geometry} material={materials.CLEARLED} position={[0.006, -0.07, -0.064]} scale={[1.348, 1.089, 1.348]} />
        <mesh geometry={nodes.Object_219.geometry} material={materials.CLEARLED} position={[0, -0.07, -0.064]} scale={[1.348, 1.089, 1.348]} />
        <mesh geometry={nodes.Object_221.geometry} material={materials.CLEARLED} position={[0.006, -0.07, -0.064]} scale={[1.348, 1.089, 1.348]} />
        <mesh geometry={nodes.Object_223.geometry} material={materials.CLEARLED} position={[0.006, -0.07, -0.064]} scale={[1.348, 1.089, 1.348]} />
        <mesh geometry={nodes.Object_225.geometry} material={materials.CLEARLED} position={[-0.002, -0.013, -0.001]} scale={1.156} />
        <mesh geometry={nodes.Object_227.geometry} material={materials.sw_rotaries} position={[0, -0.837, 0.446]} rotation={[0.087, 0, -Math.PI]} />
        <mesh geometry={nodes.Object_229.geometry} material={materials.SW_BLACK} position={[0, -0.837, 0.446]} rotation={[0.087, 0, -Math.PI]} />
        <mesh geometry={nodes.Object_231.geometry} material={materials.SW_DECALS} position={[0, -0.837, 0.446]} rotation={[0.087, 0, -Math.PI]} />
        <mesh geometry={nodes.Object_233.geometry} material={materials.SW_HANDLES} position={[0, -0.837, 0.446]} rotation={[0.087, 0, -Math.PI]} />
        <mesh geometry={nodes.Object_235.geometry} material={materials.SW_MAIN} position={[0, -0.073, -0.067]} rotation={[0.087, 0, -Math.PI]} />
        <mesh geometry={nodes.Object_237.geometry} material={materials.mercedes_decal} position={[0, -0.073, -0.068]} rotation={[0.087, 0, -Math.PI]} />
        <mesh geometry={nodes.Object_239.geometry} material={materials.SW_METAL} position={[0, -0.837, 0.446]} rotation={[0.087, 0, -Math.PI]} />
        <mesh geometry={nodes.Object_241.geometry} material={materials.SW_MONITOR_BACK} position={[0, -0.837, 0.446]} rotation={[0.087, 0, -Math.PI]} />
        <mesh geometry={nodes.Object_243.geometry} material={materials.SW_PADDLES} position={[0, -0.837, 0.446]} rotation={[0.087, 0, -Math.PI]} />
        <mesh geometry={nodes.Object_245.geometry} material={materials.SW_PLASTIC} position={[0, -0.837, 0.446]} rotation={[0.087, 0, -Math.PI]} />
        <mesh geometry={nodes.Object_247.geometry} material={materials.material_25} position={[0.053, -0.046, -0.09]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-0.008, 0.678, 0.023]} />
        <mesh geometry={nodes.Object_249.geometry} material={materials.TAG_DRS_ON} position={[0.036, -0.07, -0.063]} scale={[1.348, 1.089, 1.348]} />
        <mesh geometry={nodes.Object_251.geometry} material={materials.CLEARLED_PRE} position={[0.036, -0.07, -0.063]} scale={[1.348, 1.089, 1.348]} />
        <mesh geometry={nodes.Object_253.geometry} material={materials.CLEARLED} position={[0.019, -0.07, -0.064]} scale={[1.348, 1.089, 1.348]} />
      </group>
      <group position={[0, 0.657, -1.778]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_262.geometry} material={materials.rear_light} />
        <mesh geometry={nodes.Object_264.geometry} material={materials.generics} />
      </group>
      <group position={[0.19, 0.54, 1.683]} rotation={[-0.281, -0.112, -0.052]}>
        <mesh geometry={nodes.Object_280.geometry} material={materials.mercedes_carbon3} position={[0.021, 0.001, 0.173]} rotation={[1.85, 0.019, -0.122]} />
        <mesh geometry={nodes.Object_282.geometry} material={materials.mercedes_carbon1} position={[0.021, 0.001, 0.173]} rotation={[1.85, 0.019, -0.122]} />
        <mesh geometry={nodes.Object_284.geometry} material={materials.mercedes_carbon1} position={[0.037, -0.001, -0.125]} rotation={[1.85, 0.019, -0.122]} />
      </group>
      <group position={[-0.19, 0.54, 1.683]} rotation={[2.861, -0.112, 3.089]}>
        <mesh geometry={nodes.Object_287.geometry} material={materials.mercedes_carbon3} position={[0.021, 0.001, -0.173]} rotation={[1.292, 0.019, -3.019]} />
        <mesh geometry={nodes.Object_289.geometry} material={materials.mercedes_carbon1} position={[0.021, 0.001, -0.173]} rotation={[1.292, 0.019, -3.019]} />
        <mesh geometry={nodes.Object_291.geometry} material={materials.mercedes_carbon1} position={[0.037, -0.001, 0.125]} rotation={[1.292, 0.019, -3.019]} />
      </group>
      <group position={[0.31, 0.554, 1.713]} rotation={[0, -0.07, -0.422]}>
        <mesh geometry={nodes.Object_294.geometry} material={materials.mercedes_carbon3} position={[-0.017, 0, 0.007]} rotation={[Math.PI / 2, 0.422, -0.07]} />
        <mesh geometry={nodes.Object_296.geometry} material={materials.mercedes_carbon1} position={[-0.017, 0, 0.007]} rotation={[Math.PI / 2, 0.422, -0.07]} />
      </group>
      <group position={[-0.31, 0.554, 1.713]} rotation={[Math.PI, -0.07, 2.719]}>
        <mesh geometry={nodes.Object_299.geometry} material={materials.mercedes_carbon3} position={[-0.017, 0, -0.007]} rotation={[Math.PI / 2, 0.422, -3.072]} />
        <mesh geometry={nodes.Object_301.geometry} material={materials.mercedes_carbon1} position={[-0.017, 0, -0.007]} rotation={[Math.PI / 2, 0.422, -3.072]} />
      </group>
      <group position={[0.239, 0.379, 1.737]} rotation={[-0.123, 0.012, -0.099]}>
        <mesh geometry={nodes.Object_304.geometry} material={materials.mercedes_carbon3} position={[-0.014, -0.008, 0.123]} rotation={[1.695, 0.099, 0]} />
        <mesh geometry={nodes.Object_306.geometry} material={materials.mercedes_carbon1} position={[-0.014, -0.008, 0.123]} rotation={[1.695, 0.099, 0]} />
        <mesh geometry={nodes.Object_308.geometry} material={materials.mercedes_carbon1} position={[-0.03, 0.006, -0.256]} rotation={[1.695, 0.099, 0]} />
        <mesh geometry={nodes.Object_310.geometry} material={materials.mercedes_carbon3} position={[-0.02, -0.006, 0.219]} rotation={[1.695, 0.099, 0]} />
        <mesh geometry={nodes.Object_312.geometry} material={materials.mercedes_carbon1} position={[-0.02, -0.006, 0.219]} rotation={[1.695, 0.099, 0]} />
        <mesh geometry={nodes.Object_314.geometry} material={materials.mercedes_carbon3} position={[-0.054, -0.007, 0.125]} rotation={[1.695, 0.099, 0]} />
      </group>
      <group position={[-0.239, 0.379, 1.737]} rotation={[3.018, 0.012, 3.043]}>
        <mesh geometry={nodes.Object_317.geometry} material={materials.mercedes_carbon3} position={[-0.014, -0.008, -0.123]} rotation={[1.447, 0.099, Math.PI]} />
        <mesh geometry={nodes.Object_319.geometry} material={materials.mercedes_carbon1} position={[-0.014, -0.008, -0.123]} rotation={[1.447, 0.099, Math.PI]} />
        <mesh geometry={nodes.Object_321.geometry} material={materials.mercedes_carbon1} position={[-0.03, 0.006, 0.256]} rotation={[1.447, 0.099, Math.PI]} />
        <mesh geometry={nodes.Object_323.geometry} material={materials.mercedes_carbon3} position={[-0.02, -0.006, -0.219]} rotation={[1.447, 0.099, Math.PI]} />
        <mesh geometry={nodes.Object_325.geometry} material={materials.mercedes_carbon1} position={[-0.02, -0.006, -0.219]} rotation={[1.447, 0.099, Math.PI]} />
        <mesh geometry={nodes.Object_327.geometry} material={materials.mercedes_carbon3} position={[-0.054, -0.007, -0.125]} rotation={[1.447, 0.099, Math.PI]} />
      </group>
      <group position={[0.132, 0.44, -1.769]}>
        <mesh geometry={nodes.Object_330.geometry} material={materials.mercedes_carbon3} position={[-0.032, -0.034, -0.155]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_332.geometry} material={materials.mercedes_carbon3} position={[-0.132, 0.101, 0.039]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_334.geometry} material={materials.mercedes_carbon1} position={[0.008, 0.056, 0.358]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_336.geometry} material={materials.mercedes_carbon1} position={[-0.057, -0.132, 0.248]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_338.geometry} material={materials.mercedes_carbon3} position={[0.012, -0.063, 0.041]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_340.geometry} material={materials.mercedes_carbon3} position={[-0.066, -0.06, 0.052]} rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-0.132, 0.44, -1.769]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Object_343.geometry} material={materials.mercedes_carbon3} position={[-0.032, -0.034, 0.155]} rotation={[Math.PI / 2, 0, Math.PI]} />
        <mesh geometry={nodes.Object_345.geometry} material={materials.mercedes_carbon3} position={[-0.132, 0.101, -0.039]} rotation={[Math.PI / 2, 0, Math.PI]} />
        <mesh geometry={nodes.Object_347.geometry} material={materials.mercedes_carbon1} position={[0.008, 0.056, -0.358]} rotation={[Math.PI / 2, 0, Math.PI]} />
        <mesh geometry={nodes.Object_349.geometry} material={materials.mercedes_carbon1} position={[-0.057, -0.132, -0.248]} rotation={[Math.PI / 2, 0, Math.PI]} />
        <mesh geometry={nodes.Object_351.geometry} material={materials.mercedes_carbon3} position={[0.012, -0.063, -0.041]} rotation={[Math.PI / 2, 0, Math.PI]} />
        <mesh geometry={nodes.Object_353.geometry} material={materials.mercedes_carbon3} position={[-0.066, -0.06, -0.052]} rotation={[Math.PI / 2, 0, Math.PI]} />
      </group>
      <group position={[0, 0.466, 0.269]}>
        <mesh geometry={nodes.Object_366.geometry} material={materials.mercedes_carbon1} />
        <mesh geometry={nodes.Object_368.geometry} material={materials.mercedes_detail} />
        <mesh geometry={nodes.Object_370.geometry} material={materials.mercedes_paint} />
        <mesh geometry={nodes.Object_372.geometry} material={materials.mercedes_carbon1} />
        <mesh geometry={nodes.Object_374.geometry} material={materials.mercedes_carbon3} />
        <mesh geometry={nodes.Object_376.geometry} material={materials.mercedes_detail} />
        <mesh geometry={nodes.Object_378.geometry} material={materials.mercedes_paint} />
        <mesh geometry={nodes.Object_380.geometry} material={materials.generics} />
        <mesh geometry={nodes.Object_382.geometry} material={materials.mercedes_carbon1} />
        <mesh geometry={nodes.Object_384.geometry} material={materials.mercedes_carbon1} />
        <mesh geometry={nodes.Object_386.geometry} material={materials.mercedes_paint} />
        <mesh geometry={nodes.Object_388.geometry} material={materials.mercedes_paint} />
        <mesh geometry={nodes.Object_390.geometry} material={materials.mercedes_carbon3} />
        <mesh geometry={nodes.Object_392.geometry} material={materials.mercedes_decal} position={[0.001, 0, 0]} />
        <mesh geometry={nodes.Object_394.geometry} material={materials.mercedes_decal} position={[-0.001, 0, 0]} />
        <mesh geometry={nodes.Object_396.geometry} material={materials.mercedes_carbon3} />
        <mesh geometry={nodes.Object_398.geometry} material={materials.mercedes_paint} />
        <mesh geometry={nodes.Object_400.geometry} material={materials['erslight.001']} />
        <mesh geometry={nodes.Object_402.geometry} material={materials.mercedes_decal} position={[0, 0.001, 0]} />
        <mesh geometry={nodes.Object_404.geometry} material={materials.mercedes_carbon3} />
        <mesh geometry={nodes.Object_406.geometry} material={materials.mercedes_paint} />
        <mesh geometry={nodes.Object_408.geometry} material={materials.generics} />
        <mesh geometry={nodes.Object_410.geometry} material={materials.mercedes_paint} />
        <mesh geometry={nodes.Object_412.geometry} material={materials.generics} />
        <mesh geometry={nodes.Object_414.geometry} material={materials.mercedes_carbon1} />
      </group>
      <group position={[-0.001, 0.636, -2.141]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_421.geometry} material={materials.mercedes_carbon3} />
        <mesh geometry={nodes.Object_423.geometry} material={materials.mercedes_paint} />
      </group>
      <group position={[-0.001, 0.993, -2.352]} rotation={[Math.PI / 2, 0, 0]}>
        <group position={[0, 0.045, 0.069]}>
          <mesh geometry={nodes.Object_437.geometry} material={materials.mercedes_detail} position={[0, 0.168, 0.102]} />
        </group>
        <group position={[0, 0.003, -0.009]}>
          <mesh geometry={nodes.Object_440.geometry} material={materials.mercedes_paint} />
          <mesh geometry={nodes.Object_442.geometry} material={materials.mercedes_carbon3} />
        </group>
        <mesh geometry={nodes.Object_444.geometry} material={materials.mercedes_decal} position={[0, 0.007, -0.009]} />
        <mesh geometry={nodes.Object_446.geometry} material={materials.mercedes_decal} position={[0, 0, -0.009]} />
      </group>
      <mesh geometry={nodes.Object_449.geometry} material={materials.mercedes_carbon1} position={[0, 0.657, -1.778]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_4.geometry} material={materials.mercedes_carbon3} position={[-0.94, 0.344, 2.528]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.mercedes_carbon3} position={[0.94, 0.344, 2.528]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.generics} position={[0, 0.257, 2.711]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.mercedes_carbon1} position={[0.577, 0.284, 2.46]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.mercedes_carbon1} position={[-0.577, 0.284, 2.46]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.generics} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.generics} position={[0, 0.519, 1.909]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.generics} position={[0, 1.128, -0.051]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.mercedes_carbon1} position={[0, 0.812, 0.996]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.mercedes_paint} position={[0, 0.733, 0.453]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.mercedes_decal} position={[0, 0, 0.001]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.mercedes_carbon1} position={[-0.94, 0.344, 2.528]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.mercedes_carbon1} position={[0.94, 0.344, 2.528]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.mercedes_paint} position={[0, 0.257, 2.711]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.mercedes_detail} position={[0, 0.257, 2.711]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.mercedes_carbon1} position={[0, 0.257, 2.711]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.mercedes_carbon3} position={[0, 0.257, 2.711]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.mercedes_paint} position={[0.577, 0.284, 2.46]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.mercedes_detail} position={[0.577, 0.284, 2.46]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.mercedes_paint} position={[-0.577, 0.284, 2.46]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.mercedes_detail} position={[-0.577, 0.284, 2.46]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_46.geometry} material={materials.mercedes_detail} position={[0, 0.31, -1.815]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_48.geometry} material={materials.mercedes_paint} position={[0, 0.381, 0.85]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_50.geometry} material={materials.mercedes_paint} position={[0, 0.519, 1.909]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_52.geometry} material={materials.mercedes_detail} position={[0, 0.519, 1.909]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_54.geometry} material={materials.mercedes_carbon1} position={[0, 0.519, 1.909]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_56.geometry} material={materials.mercedes_carbon3} position={[0, 0.519, 1.909]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_58.geometry} material={materials.mercedes_detail} position={[0, 0.363, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_60.geometry} material={materials.generics} position={[0, 0.363, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_62.geometry} material={materials.mercedes_carbon1} position={[0, 1.128, -0.051]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_64.geometry} material={materials.mercedes_detail} position={[0, 1.128, -0.051]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_66.geometry} material={materials.mercedes_paint} position={[0, 0.812, 0.996]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_68.geometry} material={materials.mercedes_number} position={[0, -2.636, 0]} />
      <mesh geometry={nodes.Object_255.geometry} material={materials.mercedes_decal} position={[0.446, 0.723, 0.82]} rotation={[Math.PI / 2, 0, 0]} scale={[0.996, 1, 1]} />
      <mesh geometry={nodes.Object_257.geometry} material={materials.mercedes_decal} position={[0, -2.637, 0]} scale={100.001} />
      <mesh geometry={nodes.Object_259.geometry} material={materials.driver_color} position={[0, -2.639, 0]} scale={[100.126, 100.042, 100.042]} />
      <mesh geometry={nodes.Object_267.geometry} material={materials.mercedes_decal} position={[0.001, 0, 0]} scale={100} />
      <mesh geometry={nodes.Object_269.geometry} material={materials.mercedes_decal} position={[0, 0, 0.001]} scale={100} />
      <mesh geometry={nodes.Object_271.geometry} material={materials.mercedes_decal} position={[0, 0, 0.001]} />
      <mesh geometry={nodes.Object_273.geometry} material={materials.mercedes_decal_2} position={[0, 0.001, 0]} scale={100} />
      <mesh geometry={nodes.Object_275.geometry} material={materials.mercedes_decal} position={[-0.001, 0, 0]} scale={100} />
      <mesh geometry={nodes.Object_277.geometry} material={materials.mercedes_decal} position={[0, 0.001, 0]} scale={100} />
      <mesh geometry={nodes.Object_355.geometry} material={materials.cockpit_foam} />
      <mesh geometry={nodes.Object_357.geometry} material={materials.cockpit} />
      <mesh geometry={nodes.Object_359.geometry} material={materials.cockpit_metal} />
      <mesh geometry={nodes.Object_361.geometry} material={materials.TCAM} scale={[1.01, 1, 1]} />
      <mesh geometry={nodes.Object_363.geometry} material={materials.TCAM} scale={[1.01, 1, 1]} />
      <mesh geometry={nodes.Object_416.geometry} material={materials.mercedes_decal} position={[0, 0.001, 0]} scale={100.001} />
      <mesh geometry={nodes.Object_418.geometry} material={materials.generics} />
      <mesh geometry={nodes.Object_425.geometry} material={materials.mercedes_detail} position={[0, 0.657, -1.778]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_427.geometry} material={materials.mercedes_paint_alpha} position={[-0.001, 0.637, -2.141]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_429.geometry} material={materials.mercedes_decal} position={[-0.001, 0.636, -2.145]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_431.geometry} material={materials.mercedes_decal} position={[-0.001, 0.636, -2.141]} rotation={[Math.PI / 2, 0, 0]} scale={[1.008, 1, 1]} />
      <mesh geometry={nodes.Object_433.geometry} material={materials.mercedes_decal} position={[-0.001, 0.636, -2.141]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/assets/models/f1_2023_mercedes_amg_w14_e_performance_s1.glb')
